version: "3.9"
services:
  db: 
    image: postgres
    env_file: 
      - examples.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5433'

  web:
    build: .
    depends_on:
      - db
    ports:
      - '5000:3000'